language: cpp
script: ./configure --with-boost-python-libname=boost_python-mt-py27 && make
compiler:
 - gcc
 - clang

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libtool python2.7-dev libboost-dev libboost-python-dev libgsl0-dev python-numpy python-ply python-gtk2 python-gnome2 python-support docbook-xml docbook-utils doxygen
